language: node_js
node_js:
  - "5.3"
  - "4.2"
before_script:
  - |
      npm install -g gulp requirejs
      if [ "$TEST_ENVIRONMENT" = development ]; then
        npm install -g bower
        bower install
        gulp dependence
      fi
      gulp build --env $TEST_ENVIRONMENT
before_install:
  - npm install -g node-gyp
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_ENVIRONMENT=development
    - TEST_ENVIRONMENT=production
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
os:
  - linux
