language: node_js
node_js:
  - "5.3"
  - "4.2"
before_script:
  - npm install -g gulp bower requirejs
  - gulp production
before_install:
  - npm install -g node-gyp
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
os:
  - linux
